version: "3.9"
services:
    nginx:
        depends_on:
            - api
            - client
        restart: always
        build:
            context: ./nginx
            dockerfile: Dockerfile.dev
        ports:
            - "3050:80"
    api:
        image: online_shopping_backend
        build:
            context: ./server
            dockerfile: Dockerfile.dev
        volumes:
            - ./server:/app
            - /app/node_modules
        environment:
            - ENV_NAME=dev
    client:
        stdin_open: true
        image: online_shopping_react
        build:
            context: ./client
            dockerfile: Dockerfile.dev
        volumes:
            - ./client:/app
            - /app/node_modules
        environment:
            - VITE_ENV_NAME=dev
